version: "3.1"

services:
  db:
    build:
      context: ./
      dockerfile: db.dockerfile
    ports:
      - 5435:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d joist -h 127.0.0.1"]
      interval: 1s
      timeout: 5s
      retries: 50
